### ISSUE TITLE
[enhancement] System dir/BIOS support

### ISSUE THREAD

**Issue by rdbaaa** [Blizz9/LibretroUnity#1]
Useful for some systems, particularly any with open source/decomp'd BIOSes

**Comment by Blizz9** [comment]
Yep, this is very much needed; thank you for the submission. I think I actually had this working at some point when I was initially researching and building `CSLibretro`...so I think I could get it working pretty quickly. I am participating in a Game Jam this weekend, but I think I'll be able to get to it pretty quickly after this weekend.

**Comment by Blizz9** [comment]
This, I think, is now fixed with https://github.com/Blizz9/LibretroUnity/commit/48c2144ce13e4ffc5de95431718a452af13189af.

Let me know if you continue to see issues.

**Comment by rdbaaa** [comment]
Yep, works with Mega CD!

**Comment by Blizz9** [comment]
Awesome! Again, it still needs A LOT more work to be more full fledged, but it is a cool learning tool for anyone who is more comfortable with C# and/or Unity. rdbaaa, I think you are the only person really playing around with it, so if there are any features you want me to tackle or features to help you implement on the Unity side, please let me know. I don't think you have anything super specific in mind just yet, but this may bring some ideas to the fore for ya.
